client/src/main/java/zingg/client/Client.java, client/src/main/java/zingg/client/ZinggOptions.java, client/src/test/java/zingg/client/TestClient.java
#81 wrong value of phase shows stack trace - should be handled gracefully
=> Graceful message and exit for wrong value of phase

core/src/main/java/zingg/util/PipeUtil.java
The output location would look like : (2nd line)
2021-12-29 18:18:22,739 [main] WARN  zingg.util.PipeUtil - Reading input PARQUET
**2021-12-29 18:18:22,740 [main] WARN  zingg.util.PipeUtil - Reading location: models/1000/trainingData//unmarked/**
If entire pipe info is printed, for some scenario other information also get printed. So this option dropped
e.g.
Reading input Pipe [name=null, format=PARQUET, preprocessors=null, props={location=models/1000/trainingData//unmarked/}, schema=null]
Reading input Pipe [name=customers, format=SNOWFLAKE, preprocessors=null, props={sfUrl=tsa87485.snowflakecomputing.com, sfUser=sonalgoyal, sfPassword=ZZZZZ, sfDatabase=DEMO_DB, sfSchema=PUBLIC, sfWarehouse=COMPUTE_WH, dbtable=CUSTOMERS}, schema=null]
=> logging location of the file being read #83

client/src/main/java/zingg/client/ZinggOptions.java, core/src/main/java/zingg/LabelUpdater.java, core/src/main/java/zingg/Labeller.java, core/src/main/java/zingg/ZFactory.java
Implementation of LabelUpdater extended from labeller.
Output/Prints are similar in both the phases
Marked Records are replaced
Local Branch has been fetched from 0.3.1
=> new phase updateLabel implementation #58

core/src/main/java/zingg/Linker.java, core/src/main/java/zingg/util/DSUtil.java
addUniqueCol() is also referred to TrainingDataFinder. 
dropDuplicate() could be expansive, but perhaps necessary. Applied on data from master source only.
Note: addUniqueCol() is also duplicated in FileUtil.java, nowhere used as of now.
=> Giving same cluster id to all records linked from multiple sources #108

Dockerfile
After the change the path becomes. User can directly access zingg.sh from any place.
/zingg-0.3.1-SNAPSHOT/scripts:/opt/bitnami/python/bin:/opt/bitnami/java/bin:/opt/bitnami/spark/bin:/opt/bitnami/spark/sbin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
=> zingg.sh path included in PATH env var in Dockerfile #111

docs/setup/configuration.md, docs/stepByStep.md
Following links have been rectified. (#118)
* Create the Training Data
* linking    [match.md#link]
* Analytics -> security&privacy
=> Documentation broken links #118

core/src/main/java/zingg/util/DSUtil.java
It is fine to have z_source in the beginning in alignLinked() for better user experience. It's an end output file.
This file is mandatory for the newly generated models to test.
Reference GH-95
=> z_source column is added at the end of dataset in alignDupes 

client/src/main/java/zingg/client/Arguments.java, client/src/main/java/zingg/client/Client.java, client/src/main/java/zingg/client/ClientOptions.java, core/src/main/java/zingg/Labeller.java
Improved message if prediction is not known.
It also has collectMetrics CLI option changes.
Unimportant messages have been removed for collectMetrics case.
=> Labeller - if it is not known that it is a match or not, similarity score should not be printed #114

client/src/main/java/zingg/client/util/Util.java, core/src/main/java/zingg/Matcher.java, core/src/main/java/zingg/Trainer.java, core/src/main/java/zingg/util/BlockingTreeUtil.java, core/src/main/java/zingg/util/PipeUtil.java
"zingg.block" is a directory comprising parquet files. It was a file.
BlockingtreePipe, by default, has Overwrite mode. It should be OK in read().
=> Blocking tree are saved in parquet file #82

core/src/main/java/zingg/util/DSUtil.java, examples/febrl/configWithTrainingSamples.json, examples/febrl/training.csv
added z_source, removed id from training.csv #124
z_source has been named as "training"
All the missing fields from either DS take null value
sample records after union
=> unionByName() with allowMissingColumns=true for training data

core/src/main/java/zingg/hash/Round.java
Tested with Amazon-Google Structured data. All phases worked fine.
In the output match, the field is coming as ""
```
=======    Excerpts from /tmp/zinggOutput    =======
0.0,0.9999956199060517,11,4,production prem cs3 mac upgrad,adobe software,805.99
0.9987778680723014,0.9987778680723014,22,10,paper art : gift wrapping,arc-media-inc .,""
0.4456599013281326,0.9999956199060517,32,15,omnioutliner professional 3.0,csdc,69.95
0.0,0.47848460421892147,36,17,upg sgms 1000 incremental node,sonic-systems-inc .,"
```
=> handling null value of datatype Double #95

core/src/main/java/zingg/Labeller.java
It works like below.
e.g.
MATCH with a similarity score of {score:%f} {score:%.2f}  {newScore:%.2f}
MATCH with a similarity score of 0.965285 0.97 0.96
MATCH with a similarity score of 0.999966 1.00 0.99
=> prediction score: set precision to 2 with ~ floor mode

core/src/main/java/zingg/TrainMatcher.java
ZinggOptions set to correct value i.e. "TRAIN_MATCH" for the class
This change gives correct google analytics data.
=> In TrainMatcher class, ZinggOptions set to TRAIN_MATCH

client/src/main/java/zingg/client/pipe/Pipe.java, core/src/main/java/zingg/TrainingDataFinder.java, core/src/main/java/zingg/ZinggBase.java, core/src/main/java/zingg/util/PipeUtil.java, pom.xml
Few Points:
Compiler version - java 11 (Fixed)
Scala version 2.12.11 and above
* simple df.col(x) is not present. Also no Columns().... in snowspark, it has to get something like df.schema().names() ...  need to work further on this.
* collectAsList() is not present. rather, need to use collect(): Seq and get the needful done.
* read and write are simpler. Perhaps, most of the time have to be writeToTable() for core data.
=> Initial changes for Spark to Snowpark migration

client/src/main/java/zingg/client/Arguments.java, client/src/main/java/zingg/client/Client.java, client/src/main/java/zingg/client/ClientOptions.java, core/src/main/java/zingg/ZinggBase.java, pom.xml
New option to take connection parameters for snowflake.
The parameters can be refer to at https://docs.snowflake.com/en/developer-guide/snowpark/creating-session.html
e.g.
```
URL = https://<account_identifier>.snowflakecomputing.com
USER = <username>
PRIVATE_KEY_FILE = </path/to/private_key_file.p8>
PRIVATE_KEY_FILE_PWD = <if the private key is encrypted, set this to the passphrase for decrypting the key>
ROLE = <role_name>
WAREHOUSE = <warehouse_name>
DB = <database_name>
SCHEMA = <schema_name>
```
=> --snowflake option added to take connection paramters

client/src/main/java/zingg/client/Arguments.java, client/src/main/java/zingg/client/Client.java, client/src/main/java/zingg/client/ClientOptions.java, core/src/main/java/zingg/LabelUpdater.java, core/src/main/java/zingg/Labeller.java, core/src/main/java/zingg/util/DSUtil.java, docs/setup/configuration.md
To control the display of fields of matchType "DONT_USE" during Labelling and updateLabelling, following has been added.
a) --showConcise cli option
b) showconcise config parameter
#169
=> New option/config showconcise

docs/SUMMARY.md, docs/dataSourcesAndSinks/bigquery.md, scripts/zingg.sh
Documentation covers both read and write operation.
=> Documentation for BigQuery connector

client/pom.xml
* org.codehaus.jackson is older version of com.fasterxml.jackson. Hence, it's removed.
* jackson-core and other  dependencies require compatible version 2.12.6 as well.
=> Bump jackson-databind from 2.10.0 to 2.12.6.1 in client/pom.xml

client/pom.xml, core/src/main/java/zingg/util/PipeUtil.java, docs/dataSourcesAndSinks/snowflake.md, pom.xml
Dependencies of snowflake, mysql etc. have been removed from pom. However, their support in Zingg continues to be available. The environment varible **ZINGG_EXTRA_JARS** must be set to point to the jars of concerned data source. More in  Zingg [docs](https://docs.zingg.ai/zingg/connectors/snowflake)
=> Removed dependencies of snowflake, mysql, cassandra, elastic, apache-poi, log4j from pom

docs/settingUpZingg.md
Improved the documentation to set up the ZINGG_HOME and SPARK_HOME environment variables.
=> specify path for ZINGG_HOME

docs/settingUpZingg.md, docs/setup/installation.md
Changed to standard installation method for maven that is using "apt install".
Any version of maven shall work. Latest one should be preferred.(on date, it is 3.6.3)
=> Updated installation document to install maven using sudo apt

api/scala/FebrlExample.scala, core/src/main/java/zingg/util/PipeUtil.java
=> resolved errors

client/src/main/java/zingg/client/MatchType.java, core/src/main/java/zingg/feature/StringFeature.java, core/src/main/java/zingg/similarity/function/AffineGapSimilarityFunction.java, core/src/main/java/zingg/similarity/function/EmailMatchTypeFunction.java, core/src/main/java/zingg/similarity/function/PinCodeMatchTypeFunction.java, core/src/main/java/zingg/similarity/function/StringSimilarityDistanceFunction.java, core/src/main/java/zingg/similarity/function/StringSimilarityFunction.java, core/src/test/java/zingg/similarity/function/TestEmailMatchTypeFunction.java, core/src/test/java/zingg/similarity/function/TestPinCodeMatchTypeFunction.java
=> Match type email

scripts/zingg.sh
Tested with cluster as well.
If phase is not on the list of dictionary (hard coded), standard Zingg execution take place. In case of python phase, it shall be executed. only phase option is used as of now.
=> support for python phases in zingg.sh

Dockerfile, README.md, client/src/main/java/zingg/client/Client.java, docs/setup/installation.md, docs/setup/workingWithDocker.md, pom.xml, scripts/zingg.sh
=> Revert "release 0.3.4"

python/zingg/pipes/pipes.py
**inMemoryPipe** can be created using either Python **DataFrame** or **Pandas DataFrame**
=> inmemorypipe accepts pandas df

README.md
Hi @sonalgoyal I have fixed the broken link issue. Kindly check the same and let me know if it's done properly.
=> fixed the broken link for pipes.md

client/src/test/java/zingg/client/TestArguments.java
=> testWriteArgumentObjectToJSONFile class modification

core/src/main/java/zingg/similarity/function/DoubleSimilarityFunction.java, core/src/test/java/zingg/similarity/function/TestDoubleSimilarityFunction.java, examples/amazon-google/config.json
* fixed config.json as MatchType NUMERIC_WITH_UNITS changed to NUMBER_WITH_UNITS
* 'null' checks in DoubleSimilarityFunction. Also, checked for Double.NAN
=> Double similarity function - null pointer exception

core/src/test/java/zingg/similarity/function/TestJaccSimFunction.java
* Used JaccSimFunction class for instanciation as StringSimilarityDistanceFunction is an abstract class.
* Added TC for specific sample strings as inputs.
=> TCs for String Similarity Distance function

client/src/main/java/zingg/client/IZingg.java, client/src/main/java/zingg/client/ZFrame.java, core/src/main/java/zingg/ZinggBase.java, core/src/main/java/zingg/documenter/DataColDocumenter.java, core/src/main/java/zingg/documenter/DataDocumenter.java, core/src/main/java/zingg/documenter/DocumenterBase.java, core/src/main/java/zingg/documenter/ModelColDocumenter.java, core/src/main/java/zingg/documenter/ModelDocumenter.java, core/src/main/java/zingg/util/PipeUtilBase.java
=> adding session template

examples/febrl/configSnow.json
matchType updated from  "do_not_match" to "dont_use". It appears in the output, but no comparison is made on "dont_use". For more information, please refer to the documentation
=> matchType updated

common/client/src/main/java/zingg/common/client/util/ColName.java, common/core/src/main/resources/zColumnTemplate.ftlh, models/100/docs/model.html, models/100/docs/z_zsource.html, perf/joinPlan.txt, python/phases/exportModel.py
source column in the input leads to an error issue #415
renamed z_source to z_zsource
=> Issue 415 source column in the input leads to an error

common/client/src/main/java/zingg/common/client/ZFrame.java, common/core/src/main/java/zingg/common/core/executor/Matcher.java, spark/client/src/main/java/zingg/spark/client/SparkFrame.java, spark/client/src/test/java/zingg/client/TestSparkFrame.java
Obvious dupes performance optimisation
=> Obvious dupes performance optimisation

python/zingg/ExampleApplication.java, python/zingg/test2.py
This PR is for issue [671](https://github.com/zinggAI/zingg/issues/671)
=> try to access jvm

common/client/src/main/java/zingg/common/client/Arguments.java, common/client/src/main/java/zingg/common/client/ArgumentsUtil.java, common/client/src/main/java/zingg/common/client/Client.java, common/client/src/test/java/zingg/common/client/TestArguments.java, spark/client/src/test/java/zingg/spark/client/TestArguments.java, spark/core/src/test/java/zingg/TestDocumenter.java, spark/core/src/test/java/zingg/TestFebrlDataset.java, spark/core/src/test/java/zingg/block/TestBlock.java, spark/core/src/test/java/zingg/common/core/documenter/TestDataDocumenter.java, spark/core/src/test/java/zingg/common/core/documenter/TestModelDocumenter.java, spark/core/src/test/java/zingg/spark/core/executor/ZinggSparkTester.java
refactoring to remove use of static methods in creating Arguments and also separating util methods from config class
issue #655
=> refactoring to remove static methods in Arguments issue #655

python/zingg/client.py
issue #680 Update python api for read and write arguments to json
=> issue #680 Update python api for read and write arguments to json

assembly/dependency-reduced-pom.xml, assembly/pom.xml, common/core/pom.xml, spark/client/pom.xml, spark/core/pom.xml
This PR is for the issue [765](https://github.com/zinggAI/zingg/issues/765).
java-11-openjdk-amd64 is working for both the spark and snowflake!!
=> Update Dependencies version

common/py/src/main/java/zingg/common/py/processors/PythonClassProcessor.java, common/py/src/main/java/zingg/common/py/processors/PythonMethodProcessor.java
Now generated code is closer to the written py code.
```
import logging
from zingg.client import *
LOG = logging.getLogger("zingg.pipes")
JPipe = getJVM().zingg.spark.client.pipe.SparkPipe
FilePipe = getJVM().zingg.common.client.pipe.FilePipe
JStructType = getJVM().org.apache.spark.sql.types.StructType
class Pipe:
def __init__(self, name, format, preprocessors, props, id, dataset, schema, mode):
self.pipe = getJVM().zingg.spark.client.pipe.SparkPipe()
def setSchema(self, schema):
self.pipe.setSchema(schema)
def getName(self):
return self.pipe.getName()
def setName(self, name):
self.pipe.setName(name)
def getFormat(self):
return self.pipe.getFormat()
def setFormat(self, sinkType):
self.pipe.setFormat(sinkType)
def setProp(self, k, v):
self.pipe.setProp(k, v)
def toString(self):
return …
```
=> Update Annotations to generate code

common/client/src/main/java/zingg/common/client/FieldDefinition.java, common/client/src/main/java/zingg/common/client/cols/FieldDefSelectedCols.java, common/client/src/main/java/zingg/common/client/cols/ISelectedCols.java, common/client/src/main/java/zingg/common/client/cols/Named.java, common/client/src/main/java/zingg/common/client/cols/SelectedCols.java, common/client/src/main/java/zingg/common/client/cols/ZidAndFieldDefSelector.java
compiled and tested the TDF phase. 
Replacing old PR: [799](https://github.com/zinggAI/zingg/pull/799)
=> cols and FieldDefinition.java code changes

common/core/src/main/java/zingg/common/core/executor/Linker.java, common/core/src/main/java/zingg/common/core/executor/Matcher.java, common/core/src/main/java/zingg/common/core/pairs/IPairBuilder.java, common/core/src/main/java/zingg/common/core/pairs/SelfPairBuilder.java, common/core/src/main/java/zingg/common/core/pairs/SelfPairBuilderSourceSensitive.java
use IPairBuilder for building pairs
=> use IPairBuilder for building pairs

.gitignore, python/docs/Makefile, python/pyproject.toml, python/zingg/client.py
A temporary solution, based on the following:
- introducing a new env variable ZINGG_DRY_RUN
- if the variable is set:
+ mimic globally used JVM-stuff
+ otherwise do nothing
++ slightly update ignore and docs/Makefile
++ apply formatting to client.py
**BECAUSE OF FORMATTING THE CODE:**
- **actual changes are in lines 80-143!**
- **in reality only `getJVM` was changed, other changes related to format only!**
On branch 762-fix_sphinx_build
Changes to be committed:
modified:   .gitignore
modified:   python/docs/Makefile
new file:   python/pyproject.toml
modified:   python/zingg/client.py
Close #762
=> Make sphinx works

common/core/src/main/java/zingg/common/core/recommender/StopWordsRecommender.java
Updated error message:
`24/03/20 10:55:32 INFO StopWordsRecommender: An invalid column name - FNAME entered. Please provide valid column name, as per the config (they are case sensitive)`
=> Update error msg in StopWordsRecommender

common/client/src/main/java/zingg/common/client/event/listeners/ZinggStartListener.java, common/client/src/main/java/zingg/common/client/event/listeners/ZinggStopListener.java
Tested by running one of the phases, checked the msg absent.
This PR is for the issue [unnecessary messages in the listener](https://github.com/zinggAI/zingg/issues/809)
=> Remove unnecessary msg in listener

common/core/src/main/java/zingg/common/core/block/Block.java, common/core/src/main/java/zingg/common/core/block/Canopy.java, common/core/src/main/java/zingg/common/core/hash/FirstChars.java, spark/core/src/test/java/zingg/block/TestBlock.java
=> canopy changes

docs/deterministicMatching.md, docs/runIncremental.md
spelling corrected and added header2 issues #843
=> spelling corrected and added header2 issues #843

common/core/src/main/java/zingg/common/core/block/Block.java, spark/core/src/main/java/zingg/spark/core/block/SparkBlock.java
=> dupe code removed issue #598

python/condaRecipe/meta.yaml
this PR is for issue [651](https://github.com/zinggAI/zingg/issues/651)
i have used this meta.yaml for recipe,
command used:
conda update conda
conda install conda-build
conda info --envs
conda activate base
conda build condaRecipe
=> meta.yaml file
